
default: &default
  adapter: postgresql
  username: myshop
  password: myshop
  host: 127.0.0.1
  schema_search_path: public

development:
  <<: *default
  database: myshop_development


test:
  <<: *default
  database: myshop_test


production:
  <<: *default
  database: myshop_production
